### ISSUE TITLE
✨ Add data augmentation

### ISSUE THREAD

**Issue by socd06** [socd06/mezcal#20]
### Pain
There is a lack of robustness in the model when it comes to changes in image orientation, rotation, lighting conditions, contrast, and object location.

### Suggested Solution
Add data augmentation techniques to the make_data_loader() function to expose the model to a wider range of variations in the input data and make it more robust to the aforementioned changes.

### Tasks
- [x] Add random horizontal flipping to the batch_tfms list.
- [x] Add random rotation to the batch_tfms list.
- [x] Add random brightness to the batch_tfms list.
- [x] Add random contrast to the batch_tfms list.
- [x] Add RandomCrop to the batch_tfms list.

### More Information
You can use the aug_transforms function provided by fastai to apply augmentation.
It is worth experimenting with different combinations of data augmentation techniques and their parameters to find the best combination for your specific data set and model.

Thanks!

.

*Templates inspired by [SSWConsulting/SSW.Rules](https://github.com/SSWConsulting/SSW.Rules/blob/main/.github/ISSUE_TEMPLATE)*

**Comment by socd06** [comment]
Added item transforms and more batch augmentation
